export const COLOURS = {
  white: '#ffffff',
  black: '#000000',
  green: '#00AC76',
  red: '#C04345',
  blue: '#0043F9',
  backgroundLight: '#F0F0F3',
  backgroundMedium: '#B9B9B9',
  backgroundDark: '#777777',
};

export const Items = [
  {
    id: 1,
    category: 'product',
    productName: 'Apple iPhone 15 Pro Max',
    productPrice: 1099.99,
    description:
      'The iPhone 15 Pro Max delivers an advanced dual-camera system, stunning Super Retina XDR display, and the powerful A17 Bionic chip for incredible performance.',
    isOff: false,
    productImage: require('../storage/images/products/iphone_15_pro_max.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/products/iphone_15_pro_max.png'),
      require('../storage/images/products/iphone_15_pro_max_2.png'),
      require('../storage/images/products/iphone_15_pro_max_3.png'),
    ],
  },
  {
    id: 2,
    category: 'product',
    productName: 'Samsung Galaxy S24 Ultra',
    productPrice: 1199.99,
    description:
      'Unleash your creativity with the Samsung Galaxy S24 Ultra. Featuring a versatile quad-camera system, stunning AMOLED display, and powerful performance.',
    isOff: true,
    offPercentage: 12,
    productImage: require('../storage/images/products/galaxy_s24_ultra.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/products/galaxy_s24_ultra.png'),
      require('../storage/images/products/galaxy_s24_ultra_2.png'),
      require('../storage/images/products/galaxy_s24_ultra_3.png'),
    ],
  },
  {
    id: 3,
    category: 'product',
    productName: 'Google Pixel 8 Pro',
    productPrice: 899.99,
    description:
      'Capture stunning photos and videos with the Google Pixel 8 Pro. This smartphone features a powerful camera system, fast performance, and a beautiful OLED display.',
    isOff: false,
    productImage: require('../storage/images/products/pixel_8_pro.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/products/pixel_8_pro.png'),
      require('../storage/images/products/pixel_8_pro_2.png'),
      require('../storage/images/products/pixel_8_pro_3.png'),
    ],
  },
  {
    id: 4,
    category: 'product',
    productName: 'Sony WH-1000XM4 Wireless Headphones',
    productPrice: 349.99,
    description:
      'Experience the next level of silence with Sony WH-1000XM4. These headphones feature industry-leading noise cancellation, adaptive sound control, and comfortable design.',
    isOff: true,
    offPercentage: 15,
    productImage: require('../storage/images/products/sony_wh1000xm4.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/products/sony_wh1000xm4.png'),
      require('../storage/images/products/sony_wh1000xm4_2.png'),
      require('../storage/images/products/sony_wh1000xm4_3.png'),
    ],
  },
  {
    id: 5,
    category: 'product',
    productName: 'Bose QuietComfort 45 Wireless Headphones',
    productPrice: 329.95,
    description:
      'Immerse yourself in your music with Bose QuietComfort 45. These headphones offer world-class noise cancellation, balanced audio performance, and all-day comfort.',
    isOff: false,
    productImage: require('../storage/images/products/bose_qc45.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/products/bose_qc45.png'),
      require('../storage/images/products/bose_qc45_2.png'),
      require('../storage/images/products/bose_qc45_3.png'),
    ],
  },
  {
    id: 6,
    category: 'product',
    productName: 'Huawei Watch GT 3',
    productPrice: 229.99,
    description:
      'Stay connected and active with the Huawei Watch GT 3. Featuring a stunning AMOLED display, long battery life, and comprehensive health tracking.',
    isOff: true,
    offPercentage: 20,
    productImage: require('../storage/images/products/huawei_watch_gt3.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/products/huawei_watch_gt3.png'),
      require('../storage/images/products/huawei_watch_gt3_2.png'),
      require('../storage/images/products/huawei_watch_gt3_3.png'),
    ],
  },
  {
    id: 7,
    category: 'product',
    productName: 'Dell XPS 15 Laptop',
    productPrice: 1799.99,
    description:
      'Experience the ultimate productivity with Dell XPS 15. This laptop features a stunning 4K InfinityEdge display, powerful performance, and premium design.',
    isOff: false,
    productImage: require('../storage/images/products/dell_xps15.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/products/dell_xps15.png'),
      require('../storage/images/products/dell_xps15_2.png'),
      require('../storage/images/products/dell_xps15_3.png'),
    ],
  },
  {
    id: 8,
    category: 'product',
    productName: 'Microsoft Surface Pro 8',
    productPrice: 1099.99,
    description:
      'Maximize your productivity with Microsoft Surface Pro 8. This versatile 2-in-1 device offers the power of a laptop and the flexibility of a tablet.',
    isOff: false,
    productImage: require('../storage/images/products/surface_pro8.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/products/surface_pro8.png'),
      require('../storage/images/products/surface_pro8_2.png'),
      require('../storage/images/products/surface_pro8_3.png'),
    ],
  },
  {
    id: 9,
    category: 'product',
    productName: 'OnePlus 12',
    productPrice: 969.99,
    description:
      'Experience lightning-fast performance and stunning photography with OnePlus 12. This smartphone features Hasselblad camera technology and a smooth 120Hz display.',
    isOff: true,
    offPercentage: 8,
    productImage: require('../storage/images/products/oneplus_12.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/products/oneplus_12.png'),
      require('../storage/images/products/oneplus_12_2.png'),
      require('../storage/images/products/oneplus_12_3.png'),
    ],
  },
  {
    id: 10,
    category: 'product',
    productName: 'LG OLED C1 4K TV',
    productPrice: 1799.99,
    description:
      'Experience breathtaking visuals with LG OLED C1 4K TV. Featuring OLED technology, Dolby Vision IQ, and AI-enhanced picture and sound.',
    isOff: false,
    productImage: require('../storage/images/products/lg_oled_c1.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/products/lg_oled_c1.png'),
      require('../storage/images/products/lg_oled_c1_2.png'),
      require('../storage/images/products/lg_oled_c1_3.png'),
    ],
  },
  {
    id: 11,
    category: 'product',
    productName: 'Canon EOS R5 Mirrorless Camera',
    productPrice: 3899.99,
    description:
      'Capture stunning photos and videos with the Canon EOS R5. This mirrorless camera features a 45MP full-frame sensor, 8K video recording, and advanced autofocus.',
    isOff: true,
    offPercentage: 10,
    productImage: require('../storage/images/products/canon_eos_r5.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/products/canon_eos_r5.png'),
      require('../storage/images/products/canon_eos_r5_2.png'),
      require('../storage/images/products/canon_eos_r5_3.png'),
    ],
  },
  {
    id: 12,
    category: 'product',
    productName: 'Nintendo Switch OLED Model',
    productPrice: 349.99,
    description:
      'Experience gaming in vivid colors with the Nintendo Switch OLED Model. This upgraded version features a vibrant OLED display, enhanced audio, and improved kickstand.',
    isOff: false,
    productImage: require('../storage/images/products/nintendo_switch_oled.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/products/nintendo_switch_oled.png'),
      require('../storage/images/products/nintendo_switch_oled_2.png'),
      require('../storage/images/products/nintendo_switch_oled_3.png'),
    ],
  },
  {
    id: 13,
    category: 'accessory',
    productName: 'JBL Flip 5 Portable Bluetooth Speaker',
    productPrice: 89.99,
    description:
      'Take your music wherever you go with the JBL Flip 5. This portable Bluetooth speaker offers powerful sound, waterproof design, and up to 12 hours of playtime.',
    isOff: true,
    offPercentage: 15,
    productImage: require('../storage/images/accessories/jbl_flip5.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/accessories/jbl_flip5.png'),
      require('../storage/images/accessories/jbl_flip5_2.png'),
      require('../storage/images/accessories/jbl_flip5_3.png'),
    ],
  },
  {
    id: 14,
    category: 'accessory',
    productName: 'Samsung Galaxy Watch 4',
    productPrice: 249.99,
    description:
      'Stay connected and track your fitness with the Samsung Galaxy Watch 4. This smartwatch features advanced health monitoring, customizable watch faces, and long battery life.',
    isOff: false,
    productImage: require('../storage/images/accessories/samsung_galaxy_watch4.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/accessories/samsung_galaxy_watch4.png'),
      require('../storage/images/accessories/samsung_galaxy_watch4_2.png'),
      require('../storage/images/accessories/samsung_galaxy_watch4_3.png'),
    ],
  },
  {
    id: 15,
    category: 'accessory',
    productName: 'Bose SoundSport Wireless Earbuds',
    productPrice: 129.99,
    description:
      'Stay motivated during workouts with Bose SoundSport wireless earbuds. These earbuds offer powerful sound, secure fit, and sweat resistance.',
    isOff: false,
    productImage: require('../storage/images/accessories/bose_soundsport.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/accessories/bose_soundsport.png'),
      require('../storage/images/accessories/bose_soundsport_2.png'),
      require('../storage/images/accessories/bose_soundsport_3.png'),
    ],
  },
  {
    id: 16,
    category: 'accessory',
    productName: 'Fitbit Charge 5 Fitness Tracker',
    productPrice: 179.99,
    description:
      'Track your health and fitness goals with the Fitbit Charge 5. This fitness tracker offers advanced heart rate monitoring, GPS, sleep tracking, and more.',
    isOff: true,
    offPercentage: 10,
    productImage: require('../storage/images/accessories/fitbit_charge5.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/accessories/fitbit_charge5.png'),
      require('../storage/images/accessories/fitbit_charge5_2.png'),
      require('../storage/images/accessories/fitbit_charge5_3.png'),
    ],
  },
  {
    id: 17,
    category: 'accessory',
    productName: 'Anker PowerCore 26800 Portable Charger',
    productPrice: 59.99,
    description:
      'Stay powered up on the go with the Anker PowerCore 26800. This portable charger offers high-speed charging, massive capacity, and multiple charging ports.',
    isOff: false,
    productImage: require('../storage/images/accessories/anker_powercore.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/accessories/anker_powercore.png'),
      require('../storage/images/accessories/anker_powercore_2.png'),
      require('../storage/images/accessories/anker_powercore_3.png'),
    ],
  },
  {
    id: 18,
    category: 'accessory',
    productName: 'Razer DeathAdder V2 Gaming Mouse',
    productPrice: 69.99,
    description:
      'Dominate your opponents with the Razer DeathAdder V2. This gaming mouse features a high-precision sensor, ergonomic design, and customizable RGB lighting.',
    isOff: true,
    offPercentage: 20,
    productImage: require('../storage/images/accessories/razer_deathadder_v2.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/accessories/razer_deathadder_v2.png'),
      require('../storage/images/accessories/razer_deathadder_v2_2.png'),
      require('../storage/images/accessories/razer_deathadder_v2_3.png'),
    ],
  },
  {
    id: 19,
    category: 'accessory',
    productName: 'Logitech G Pro X Gaming Headset',
    productPrice: 129.99,
    description:
      'Immerse yourself in the game with the Logitech G Pro X. This gaming headset offers advanced audio technology, comfortable design, and customizable sound profiles.',
    isOff: false,
    productImage: require('../storage/images/accessories/logitech_gprox.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/accessories/logitech_gprox.png'),
      require('../storage/images/accessories/logitech_gprox_2.png'),
      require('../storage/images/accessories/logitech_gprox_3.png'),
    ],
  },
  {
    id: 20,
    category: 'accessory',
    productName: 'Amazon Kindle Paperwhite',
    productPrice: 129.99,
    description:
      'Enjoy reading anywhere with the Amazon Kindle Paperwhite. This e-reader features a high-resolution display, adjustable front light, and long battery life.',
    isOff: false,
    productImage: require('../storage/images/accessories/kindle_paperwhite.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/accessories/kindle_paperwhite.png'),
      require('../storage/images/accessories/kindle_paperwhite_2.png'),
      require('../storage/images/accessories/kindle_paperwhite_3.png'),
    ],
  },
  {
    id: 21,
    category: 'accessory',
    productName: 'Tile Mate Bluetooth Tracker',
    productPrice: 24.99,
    description:
      'Never lose your belongings again with the Tile Mate. This Bluetooth tracker helps you find your keys, wallet, or any other item with ease.',
    isOff: false,
    productImage: require('../storage/images/accessories/tile_mate.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/accessories/tile_mate.png'),
      require('../storage/images/accessories/tile_mate_2.png'),
      require('../storage/images/accessories/tile_mate_3.png'),
    ],
  },
  {
    id: 22,
    category: 'accessory',
    productName: 'Nomad Base Station Pro Wireless Charger',
    productPrice: 199.99,
    description:
      'Charge your devices wirelessly with the Nomad Base Station Pro. This wireless charger offers multi-device charging, premium materials, and sleek design.',
    isOff: true,
    offPercentage: 10,
    productImage: require('../storage/images/accessories/nomad_base_station.png'),
    isAvailable: true,
    productImageList: [
      require('../storage/images/accessories/nomad_base_station.png'),
      require('../storage/images/accessories/nomad_base_station_2.png'),
      require('../storage/images/accessories/nomad_base_station_3.png'),
    ],
  },
];
